### PR TITLE
Use today's date as the default for onetime's date

### PR DESCRIPTION
**Pull request by farzadmf**

### CODE REVIEW

**Comment by skanehira** [comment]
LGTM :)

**Comment by farzadmf** [comment]
Hey @skanehira , how are the releases created? Seems like this change is not released yet

**Comment by skanehira** [comment]
@farzadmf Sorry I'm so lated.
I pushed v0.1.1 that includes this change.

**Comment by farzadmf** [comment]
Cool, thanks @skanehira , I'd forgotten about it :laughing:

**Pull request merged**
